#' add_header
#' Helper function to make the first column the header.
#' This is linked to preparing the query data when manually entered in the app.
#' @param df user data.frame generated by manual data entry in the app.
#'
#' @return A re-formatted data.frame with header based on column names
#' @export
#'
#' @examples
#' \dontrun{
#' add_header(user_df)
#' }
add_header <- function(df) {
  names(df) <- as.character(unlist(df[1, ]))
  df[-1, ]
}
