# app modules
#-----------------------------------------global UI options------------------------------------------
options(spinner.type = 1, spinner.color = "#232a30", spinner.size = 2)


#-------------------------------------------UI-----------------------------------------------------

myModuleUI <- function(id) {
  ns <- NS(id)

  sidebarLayout(
    sidebarPanel(
      width = 3,
      textInput(
        inputId = ns("amel"),
        label = "Amel",
        # placeholder = "X",
      ),
      textInput(
        inputId = ns("csf1po"),
        label = "CSF1PO",
      ),
      textInput(
        inputId = ns("d10s1248"),
        label = "D10S1248",
      ),
      textInput(
        inputId = ns("d12s391"),
        label = "D12S391",
      ),
      textInput(
        inputId = ns("d13s317"),
        label = "D13s317",
      ),
      textInput(
        inputId = ns("d16s539"),
        label = "D16s539",
      ),
      textInput(
        inputId = ns("d18s51"),
        label = "D18s51",
      ),
      textInput(
        inputId = ns("d19s433"),
        label = "D19S433",
      ),
      textInput(
        inputId = ns("d1s1656"),
        label = "D1S1656",
      ),
      textInput(
        inputId = ns("d21s11"),
        label = "D21s11",
      ),
      textInput(
        inputId = ns("d22s1045"),
        label = "D22S1045",
      ),
      textInput(
        inputId = ns("d2s1338"),
        label = "D2S1338",
      ),
      textInput(
        inputId = ns("d2s441"),
        label = "D2S441",
      ),
      textInput(
        inputId = ns("d3s1358"),
        label = "D3s1358",
      ),
      textInput(
        inputId = ns("d5s818"),
        label = "D5s818",
      ),
      textInput(
        inputId = ns("d7s820"),
        label = "D7s820",
      ),
      textInput(
        inputId = ns("d8s1179"),
        label = "D8s1179",
      ),
      textInput(
        inputId = ns("dys391"),
        label = "DYS391",
      ),
      textInput(
        inputId = ns("fga"),
        label = "FGA",
      ),
      textInput(
        inputId = ns("penta.d"),
        label = "Penta.D",
      ),
      textInput(
        inputId = ns("penta.e"),
        label = "Penta.E",
      ),
      textInput(
        inputId = ns("th01"),
        label = "TH01",
      ),
      textInput(
        inputId = ns("tpox"),
        label = "TPOX",
      ),
      textInput(
        inputId = ns("vwa"),
        label = "vWA",
      ),
      actionButton(
        inputId = ns("go"),
        label = "Search",
        icon("dna"),
        style = "color: #ededed; background-color: #232a30"
      ),
    ),
    mainPanel(
      width = 9, style = main_panel_style,
      DT::DTOutput(ns("filtered_data")) # %>%
      #   shinycssloaders::withSpinner(),
      # ns = ns
    )
  )
}


#-------------------------------------------SERVER-----------------------------------------------------

## TODO: move score or other relevant data to earlier columns in table below
# for easier visibility
## TODO: query below should be concat of all options
## TODO: add in option (in UI above) for algorithm choice
## TODO: provide option to add NA (but NA read as character so convert to NA) and/or keep as it (leave blank)
## ^ use dplyr::na_if ; e.g. na_if("NA, "NA") ; https://dplyr.tidyverse.org/reference/na_if.html

myModuleServer <- function(id, dataset) {
  moduleServer(
    id,
    function(input, output, session) {
      # output$result <- renderText({
      #   paste0(prefix, toupper(input$txt))
      # })

      output$filtered_data <- DT::renderDT({
        #-----------------test----------------------
        ## TODO: query_test below is placeholder generated by
        # query_test <- gbmpdx_ref[1,]
        # rownames(query_test) <- "query"
        # DT::datatable(process_query(query = query_test),
        #               rownames = FALSE,
        #               options = list(pageLength = 10,
        #                              scrollX = TRUE),
        #               escape = FALSE) # to not escape HTML code in table
        #-----------------end test----------------------
        # TODO: automate the below - just testing for now
        # https://stackoverflow.com/questions/40044768/addressing-multiple-inputs-in-shiny

        #NOTE: I noticed a strange lock/lag after several submits with eventReactive
        # which is not present when eventReactive is not used. Explore this further
        update_query <- eventReactive(input$go, {
          c(
            input$amel,
            input$csf1po,
            input$d10s1248,
            input$d12s391,
            input$d13s317,
            input$d16s539,
            input$d18s51,
            input$d19s433,
            input$d1s1656,
            input$d21s11,
            input$d22s1045,
            input$d2s1338,
            input$d2s441,
            input$d3s1358,
            input$d5s818,
            input$d7s820,
            input$d8s1179,
            input$dys391,
            input$fga,
            input$penta.d,
            input$penta.e,
            input$th01,
            input$tpox,
            input$vwa
          )
        })

        # input_data <-c(
        #     input$amel,
        #     input$csf1po,
        #     input$d10s1248,
        #     input$d12s391,
        #     input$d13s317,
        #     input$d16s539,
        #     input$d18s51,
        #     input$d19s433,
        #     input$d1s1656,
        #     input$d21s11,
        #     input$d22s1045,
        #     input$d2s1338,
        #     input$d2s441,
        #     input$d3s1358,
        #     input$d5s818,
        #     input$d7s820,
        #     input$d8s1179,
        #     input$dys391,
        #     input$fga,
        #     input$penta.d,
        #     input$penta.e,
        #     input$th01,
        #     input$tpox,
        #     input$vwa)

        # create query d.f (order matches marker input)

        #user_df <- data.frame(markers_ref, input_data)
        user_df <- data.frame(markers_ref, update_query())
        user_df <- as.data.frame(t(user_df))
        user_df <- add_header(user_df)

        DT::datatable(process_query(query = user_df),
          rownames = FALSE,
          options = list(
            pageLength = 10,
            scrollX = TRUE
          ),
          escape = FALSE
        ) # to not escape HTML code in table
      })
    }
  )
}
